import { Device, Zone } from "./types";

export const mockZones: Zone[] = [
  {
    id: "zone-001",
    name: "Parlor",
    description: "Main living and entertainment area",
    icon: "sofa",
    floor: "Ground Floor",
    devices: ["light-1", "light-2", "socket-1", "socket-2", "ac-3"],
    position: { x: 0, y: 0 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "zone-002",
    name: "Master Bedroom",
    description: "Primary bedroom suite",
    icon: "bed",
    floor: "Ground Floor",
    devices: ["ac-1", "light-3", "socket-3", "socket-4"],
    position: { x: 1, y: 0 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "zone-003",
    name: "Children's Room",
    description: "Kids' bedroom and play area",
    icon: "baby",
    floor: "Ground Floor",
    devices: ["light-4", "socket-5", "socket-6", "fan-1"],
    position: { x: 0, y: 1 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "zone-004",
    name: "Store Room",
    description: "Storage and utility area",
    icon: "box",
    floor: "Ground Floor",
    devices: ["light-5", "socket-7", "socket-8", "fan-2", "inverter-1"],
    position: { x: 1, y: 1 },
    createdAt: new Date().toISOString(),
  },
];

export const mockDevices: Device[] = [
  {
    id: "ac-1",
    name: "Master AC",
    zoneId: "zone-002",
    type: "AC",
    status: "online",
    powerState: "on",
    lastActivity: "2 minutes ago",
    temperature: 22,
    mode: "Cool",
    fanSpeed: "Auto",
    todayUsage: 1.2,
    energyHistory: [
      { time: "00:00", usage: 0.5 },
      { time: "04:00", usage: 0.8 },
      { time: "08:00", usage: 1.2 },
      { time: "12:00", usage: 0.9 },
      { time: "16:00", usage: 1.5 },
      { time: "20:00", usage: 1.1 },
    ],
  },
  {
    id: "inverter-1",
    name: "Main Inverter",
    zoneId: "zone-004",
    type: "Inverter",
    status: "online",
    powerState: "on",
    lastActivity: "Just now",
    batteryPercentage: 92,
    batteryHealth: 98,
    inputVoltage: 228,
    outputVoltage: 220,
    loadPercentage: 35,
    backupTime: "8h 32m",
    chargingStatus: "Charging",
  },
  {
    id: "light-1",
    name: "Chandelier",
    zoneId: "zone-001",
    type: "Light",
    status: "online",
    powerState: "on",
    lastActivity: "15 minutes ago",
  },
  {
    id: "light-2",
    name: "Parlor Recessed",
    zoneId: "zone-001",
    type: "Light",
    status: "online",
    powerState: "off",
    lastActivity: "1 hour ago",
  },
  {
    id: "socket-1",
    name: "TV Socket",
    zoneId: "zone-001",
    type: "Socket",
    status: "online",
    powerState: "on",
    lastActivity: "Just now",
    consumption: 45,
  },
  {
    id: "socket-2",
    name: "Sound System",
    zoneId: "zone-001",
    type: "Socket",
    status: "online",
    powerState: "off",
    lastActivity: "3 hours ago",
    consumption: 0,
  },
  {
    id: "ac-3",
    name: "Parlor AC",
    zoneId: "zone-001",
    type: "AC",
    status: "online",
    powerState: "off",
    lastActivity: "Yesterday",
    temperature: 24,
    mode: "Eco",
    fanSpeed: "Low",
    todayUsage: 0,
    energyHistory: [],
  },
  {
    id: "light-3",
    name: "Bedside Lamp",
    zoneId: "zone-002",
    type: "Light",
    status: "offline",
    powerState: "off",
    lastActivity: "2 days ago",
  },
  {
    id: "socket-3",
    name: "Master Socket 1",
    zoneId: "zone-002",
    type: "Socket",
    status: "online",
    powerState: "on",
    lastActivity: "Just now",
  },
  {
    id: "socket-4",
    name: "Master Socket 2",
    zoneId: "zone-002",
    type: "Socket",
    status: "online",
    powerState: "on",
    lastActivity: "Just now",
  },
  {
    id: "light-4",
    name: "Kids Ceiling Light",
    zoneId: "zone-003",
    type: "Light",
    status: "online",
    powerState: "on",
    lastActivity: "5 minutes ago",
  },
  {
    id: "socket-5",
    name: "Kids Socket 1",
    zoneId: "zone-003",
    type: "Socket",
    status: "online",
    powerState: "off",
    lastActivity: "1 hour ago",
  },
  {
    id: "socket-6",
    name: "Kids Socket 2",
    zoneId: "zone-003",
    type: "Socket",
    status: "online",
    powerState: "off",
    lastActivity: "1 hour ago",
  },
  {
    id: "fan-1",
    name: "Kids Ceiling Fan",
    zoneId: "zone-003",
    type: "Fan",
    status: "online",
    powerState: "off",
    lastActivity: "2 hours ago",
    fanSpeed: "Medium",
  },
  {
    id: "light-5",
    name: "Store Light",
    zoneId: "zone-004",
    type: "Light",
    status: "online",
    powerState: "off",
    lastActivity: "Yesterday",
  },
  {
    id: "socket-7",
    name: "Store Socket 1",
    zoneId: "zone-004",
    type: "Socket",
    status: "online",
    powerState: "on",
    lastActivity: "Always On",
  },
  {
    id: "socket-8",
    name: "Store Socket 2",
    zoneId: "zone-004",
    type: "Socket",
    status: "online",
    powerState: "on",
    lastActivity: "Always On",
  },
  {
    id: "fan-2",
    name: "Store Exhaust",
    zoneId: "zone-004",
    type: "Fan",
    status: "online",
    powerState: "on",
    lastActivity: "Just now",
    fanSpeed: "High",
  },
];
