import { Device } from "./types";

export const mockDevices: Device[] = [
  {
    id: "ac-1",
    name: "Master AC",
    room: "Master Bedroom",
    type: "AC",
    online: true,
    active: true,
    lastActivity: "2 minutes ago",
    temperature: 22,
    mode: "Cool",
    fanSpeed: "Auto",
    todayUsage: 1.2,
    energyHistory: [
      { time: "00:00", usage: 0.5 },
      { time: "04:00", usage: 0.8 },
      { time: "08:00", usage: 1.2 },
      { time: "12:00", usage: 0.9 },
      { time: "16:00", usage: 1.5 },
      { time: "20:00", usage: 1.1 },
    ],
  },
  {
    id: "inverter-1",
    name: "Main Inverter",
    room: "Store Room",
    type: "Inverter",
    online: true,
    active: true,
    lastActivity: "Just now",
    batteryPercentage: 92,
    batteryHealth: 98,
    inputVoltage: 228,
    outputVoltage: 220,
    loadPercentage: 35,
    backupTime: "8h 32m",
    chargingStatus: "Charging",
  },
  {
    id: "light-1",
    name: "Chandelier",
    room: "Parlor",
    type: "Light",
    online: true,
    active: true,
    lastActivity: "15 minutes ago",
  },
  {
    id: "fan-1",
    name: "Ceiling Fan",
    room: "Children's Room",
    type: "Fan",
    online: true,
    active: false,
    lastActivity: "1 hour ago",
    fanSpeed: "Medium",
  },
  {
    id: "socket-1",
    name: "Entertainment Hub",
    room: "Parlor",
    type: "Socket",
    online: true,
    active: true,
    lastActivity: "Today • 10:45 AM",
    consumption: 45,
  },
  {
    id: "ac-2",
    name: "Guest AC",
    room: "Guest Room",
    type: "AC",
    online: true,
    active: false,
    lastActivity: "Yesterday • 8:12 PM",
    temperature: 24,
    mode: "Eco",
    fanSpeed: "Low",
    todayUsage: 0.8,
    energyHistory: [
      { time: "00:00", usage: 0.2 },
      { time: "04:00", usage: 0.3 },
      { time: "08:00", usage: 0.5 },
      { time: "12:00", usage: 0.4 },
      { time: "16:00", usage: 0.6 },
      { time: "20:00", usage: 0.3 },
    ],
  },
  {
    id: "light-2",
    name: "Bedside Lamp",
    room: "Master Bedroom",
    type: "Light",
    online: false,
    active: false,
    lastActivity: "2 days ago",
  },
];
