/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FloorPlanRouteImport } from './routes/floor-plan'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZonesIndexRouteImport } from './routes/zones.index'
import { Route as ZonesZoneIdRouteImport } from './routes/zones.$zoneId'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlanRoute = FloorPlanRouteImport.update({
  id: '/floor-plan',
  path: '/floor-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesIndexRoute = ZonesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZonesRoute,
} as any)
const ZonesZoneIdRoute = ZonesZoneIdRouteImport.update({
  id: '/$zoneId',
  path: '/$zoneId',
  getParentRoute: () => ZonesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/floor-plan': typeof FloorPlanRoute
  '/notifications': typeof NotificationsRoute
  '/scenes': typeof ScenesRoute
  '/settings': typeof SettingsRoute
  '/zones': typeof ZonesRouteWithChildren
  '/zones/$zoneId': typeof ZonesZoneIdRoute
  '/zones/': typeof ZonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/floor-plan': typeof FloorPlanRoute
  '/notifications': typeof NotificationsRoute
  '/scenes': typeof ScenesRoute
  '/settings': typeof SettingsRoute
  '/zones/$zoneId': typeof ZonesZoneIdRoute
  '/zones': typeof ZonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/floor-plan': typeof FloorPlanRoute
  '/notifications': typeof NotificationsRoute
  '/scenes': typeof ScenesRoute
  '/settings': typeof SettingsRoute
  '/zones': typeof ZonesRouteWithChildren
  '/zones/$zoneId': typeof ZonesZoneIdRoute
  '/zones/': typeof ZonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/devices'
    | '/floor-plan'
    | '/notifications'
    | '/scenes'
    | '/settings'
    | '/zones'
    | '/zones/$zoneId'
    | '/zones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/devices'
    | '/floor-plan'
    | '/notifications'
    | '/scenes'
    | '/settings'
    | '/zones/$zoneId'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/devices'
    | '/floor-plan'
    | '/notifications'
    | '/scenes'
    | '/settings'
    | '/zones'
    | '/zones/$zoneId'
    | '/zones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DevicesRoute: typeof DevicesRoute
  FloorPlanRoute: typeof FloorPlanRoute
  NotificationsRoute: typeof NotificationsRoute
  ScenesRoute: typeof ScenesRoute
  SettingsRoute: typeof SettingsRoute
  ZonesRoute: typeof ZonesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plan': {
      id: '/floor-plan'
      path: '/floor-plan'
      fullPath: '/floor-plan'
      preLoaderRoute: typeof FloorPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/': {
      id: '/zones/'
      path: '/'
      fullPath: '/zones/'
      preLoaderRoute: typeof ZonesIndexRouteImport
      parentRoute: typeof ZonesRoute
    }
    '/zones/$zoneId': {
      id: '/zones/$zoneId'
      path: '/$zoneId'
      fullPath: '/zones/$zoneId'
      preLoaderRoute: typeof ZonesZoneIdRouteImport
      parentRoute: typeof ZonesRoute
    }
  }
}

interface ZonesRouteChildren {
  ZonesZoneIdRoute: typeof ZonesZoneIdRoute
  ZonesIndexRoute: typeof ZonesIndexRoute
}

const ZonesRouteChildren: ZonesRouteChildren = {
  ZonesZoneIdRoute: ZonesZoneIdRoute,
  ZonesIndexRoute: ZonesIndexRoute,
}

const ZonesRouteWithChildren = ZonesRoute._addFileChildren(ZonesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DevicesRoute: DevicesRoute,
  FloorPlanRoute: FloorPlanRoute,
  NotificationsRoute: NotificationsRoute,
  ScenesRoute: ScenesRoute,
  SettingsRoute: SettingsRoute,
  ZonesRoute: ZonesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
